project:
  type: website

website:
  title: "Levi Fikri"
  navbar:
    search: true
    background: "danger"
    right: 
      - text: "Fun Visual Coding"
        href: "fun-visual-coding/introduction.md"
      - text: "Competitive Programming"
        href: "competitive-programming/introduction.ipynb"
    pinned: true
  bread-crumbs: false
  sidebar:
    style: "floating"
    collapse-level: 3
    border: true
    contents: 
      - section: "Fun Visual Coding"
        contents: "fun-visual-coding/*"
      - text: "---"
      - section: "Competitive Programming"
        contents:
          - "competitive-programming/introduction.ipynb"
          - "competitive-programming/philosophy.ipynb"
          - section: "Data Structure"
            contents: "competitive-programming/data-structure/*.ipynb"
          - section: "Algorithm"
            contents: "competitive-programming/algorithm/*"
          - section: "Cryptography"
            contents: "competitive-programming/cryptography/*"
  twitter-card: true
  open-graph: true

format:
  html:
    theme: default
    # theme: lumen
    # theme: materia
    # theme: united
    # theme: zephyr
    css: styles.css
    toc: true