project:
  type: website
  resources:
    - "slides/state-of-ai-2025/style.css"
    - "slides/state-of-ai-2025/app.js"
    - "slides/state-of-ai-2025/assets/"
    - "slides/state-of-ai-2025/visualizations/"

website:
  title: "Levi Fikri"
  google-analytics: "G-HZ27R5K5M2"
  navbar:
    search: true
    background: "danger"
    right: 
      - text: "Fun Visual Coding"
        href: "fun-visual-coding/introduction.md"
      - text: "Competitive Programming"
        href: "competitive-programming/introduction.ipynb"
      - text: "Demystifying Rust"
        href: "rust/introduction.ipynb"
    pinned: true
  bread-crumbs: false
  sidebar:
    style: "floating"
    collapse-level: 3
    border: true
    contents: 
      - section: "Presentations"
        contents:
        - text: "AI & Education"
          href: "slides/state-of-ai-2025/index.html"
        - text: "Vibe Coding @2025"
          href: "slides/vibe-coding-2025/index.html"
      - text: "---"
      - section: "Demystifying Rust"
        contents: "rust/*.ipynb"
      - text: "---"
      - section: "Competitive Programming"
        contents:
          - "competitive-programming/introduction.ipynb"
          - "competitive-programming/philosophy.ipynb"
          - section: "Data Structure"
            contents: "competitive-programming/data-structure/*.ipynb"
          - section: "Algorithm"
            contents: "competitive-programming/algorithm/*"
          - section: "Cryptography"
            contents: "competitive-programming/cryptography/*"
      - text: "---"
      - section: "Fun Visual Coding"
        contents: "fun-visual-coding/*"
  twitter-card: true
  open-graph: true

format:
  html:
    theme: default
    # theme: lumen
    # theme: materia
    # theme: united
    # theme: zephyr
    css: styles.css
    toc: true
    toc-depth: 4
    toc-expand: true